-- ============================================================
-- KIRTI PHARMA — SUPABASE (POSTGRESQL) SCHEMA & SEED DATA
-- Copy and paste this directly into Supabase "SQL Editor" -> Click "Run"
-- ============================================================

-- 1. MEDICINES TABLE (Tracks Inventory Stock & Total Units Sold)
CREATE TABLE IF NOT EXISTS public.medicines (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  salt TEXT,
  brand TEXT,
  category TEXT,
  price NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  mrp NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  stock INT NOT NULL DEFAULT 0,
  sold INT NOT NULL DEFAULT 0,
  packSize INT DEFAULT 10,
  packUnit TEXT DEFAULT 'tablets',
  prescription_required BOOLEAN DEFAULT FALSE,
  chronic BOOLEAN DEFAULT FALSE,
  imageColor TEXT DEFAULT '#FEE2E2',
  icon TEXT DEFAULT '💊',
  image TEXT DEFAULT 'images/med_fever_pain.png',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. ORDERS TABLE
CREATE TABLE IF NOT EXISTS public.orders (
  id TEXT PRIMARY KEY,
  customerName TEXT NOT NULL,
  phone TEXT NOT NULL,
  date TEXT,
  placed TEXT,
  status TEXT DEFAULT 'confirmed',
  paymentMethod TEXT DEFAULT 'UPI',
  paymentStatus TEXT DEFAULT 'Paid',
  deliveryAddress TEXT,
  items JSONB,
  subtotal NUMERIC(10,2) DEFAULT 0.00,
  deliveryFee NUMERIC(10,2) DEFAULT 0.00,
  total NUMERIC(10,2) DEFAULT 0.00,
  prescriptionId INT,
  notes TEXT,
  rider JSONB,
  stages JSONB,
  estimatedDelivery TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. PRESCRIPTIONS TABLE
CREATE TABLE IF NOT EXISTS public.prescriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient TEXT NOT NULL,
  initials TEXT DEFAULT 'PT',
  phone TEXT,
  source TEXT DEFAULT 'App',
  status TEXT DEFAULT 'Pending',
  color TEXT DEFAULT '#7C3AED',
  time TEXT,
  date TEXT DEFAULT 'Today',
  fileName TEXT,
  fileUrl TEXT,
  notes TEXT,
  bill JSONB,
  orderId TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. USERS TABLE
CREATE TABLE IF NOT EXISTS public.users (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT UNIQUE NOT NULL,
  email TEXT,
  role TEXT DEFAULT 'customer',
  addresses JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ENABLE PUBLIC ACCESS POLICIES (Allow App to Read/Write)
ALTER TABLE public.medicines ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public access to medicines" ON public.medicines;
CREATE POLICY "Public access to medicines" ON public.medicines FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public access to orders" ON public.orders;
CREATE POLICY "Public access to orders" ON public.orders FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.prescriptions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public access to prescriptions" ON public.prescriptions;
CREATE POLICY "Public access to prescriptions" ON public.prescriptions FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public access to users" ON public.users;
CREATE POLICY "Public access to users" ON public.users FOR ALL USING (true) WITH CHECK (true);

-- SEED 58 VERIFIED MEDICINES WITH STOCK AND SALES
INSERT INTO public.medicines (id, name, salt, brand, category, price, mrp, stock, sold, packSize, packUnit, prescription_required, chronic, imageColor, icon, image) VALUES
(1, 'Crocin 650mg', 'Paracetamol 650mg', 'GSK', 'Fever & Pain', 32.00, 38.00, 48, 124, 15, 'tablets', false, false, '#FEE2E2', '💊', 'images/med_fever_pain.png'),
(2, 'Dolo 650', 'Paracetamol 650mg', 'Micro Labs', 'Fever & Pain', 28.00, 34.00, 60, 185, 15, 'tablets', false, false, '#FEE2E2', '💊', 'images/med_fever_pain.png'),
(3, 'Combiflam', 'Ibuprofen 400mg + Paracetamol 325mg', 'Sanofi', 'Fever & Pain', 42.00, 50.00, 35, 92, 20, 'tablets', false, false, '#FEE2E2', '💊', 'images/med_fever_pain.png'),
(4, 'Brufen 400mg', 'Ibuprofen 400mg', 'Abbott', 'Fever & Pain', 38.00, 45.00, 22, 45, 15, 'tablets', false, false, '#FEE2E2', '💊', 'images/med_fever_pain.png'),
(5, 'Nimulid 100mg', 'Nimesulide 100mg', 'Panacea Biotech', 'Fever & Pain', 55.00, 65.00, 18, 34, 10, 'tablets', false, false, '#FEE2E2', '💊', 'images/med_fever_pain.png'),
(6, 'Voveran 50mg', 'Diclofenac Sodium 50mg', 'Novartis', 'Fever & Pain', 48.00, 58.00, 14, 61, 10, 'tablets', false, false, '#FEE2E2', '💊', 'images/med_fever_pain.png'),
(7, 'Sumo', 'Nimesulide 100mg + Paracetamol 325mg', 'Mankind', 'Fever & Pain', 35.00, 42.00, 30, 78, 10, 'tablets', false, false, '#FEE2E2', '💊', 'images/med_fever_pain.png'),
(8, 'Zerodol-P', 'Aceclofenac 100mg + Paracetamol 325mg', 'Ipca', 'Fever & Pain', 62.00, 75.00, 20, 88, 10, 'tablets', false, false, '#FEE2E2', '💊', 'images/med_fever_pain.png'),
(9, 'Azithral 500mg', 'Azithromycin 500mg', 'Alembic', 'Antibiotics', 89.00, 105.00, 15, 53, 5, 'tablets', true, false, '#FEF3C7', '💊', 'images/med_antibiotics.png'),
(10, 'Augmentin 625', 'Amoxicillin 500mg + Clavulanic Acid 125mg', 'GSK', 'Antibiotics', 198.00, 235.00, 10, 40, 10, 'tablets', true, false, '#FEF3C7', '💊', 'images/med_antibiotics.png'),
(11, 'Cifran 500', 'Ciprofloxacin 500mg', 'Sun Pharma', 'Antibiotics', 78.00, 92.00, 18, 31, 10, 'tablets', true, false, '#FEF3C7', '💊', 'images/med_antibiotics.png'),
(12, 'Mox 500', 'Amoxicillin 500mg', 'Ranbaxy', 'Antibiotics', 65.00, 78.00, 25, 44, 10, 'tablets', true, false, '#FEF3C7', '💊', 'images/med_antibiotics.png'),
(13, 'Taxim-O 200', 'Cefixime 200mg', 'Alkem', 'Antibiotics', 145.00, 172.00, 12, 29, 10, 'tablets', true, false, '#FEF3C7', '💊', 'images/med_antibiotics.png'),
(14, 'Zenflox 200', 'Ofloxacin 200mg', 'Mankind', 'Antibiotics', 58.00, 68.00, 20, 37, 10, 'tablets', true, false, '#FEF3C7', '💊', 'images/med_antibiotics.png'),
(15, 'Clavam 625', 'Amoxicillin 500mg + Clavulanic Acid 125mg', 'Alkem', 'Antibiotics', 188.00, 224.00, 8, 22, 10, 'tablets', true, false, '#FEF3C7', '💊', 'images/med_antibiotics.png'),
(16, 'Metrogyl 400', 'Metronidazole 400mg', 'JB Chem', 'Antibiotics', 42.00, 50.00, 32, 58, 15, 'tablets', true, false, '#FEF3C7', '💊', 'images/med_antibiotics.png'),
(17, 'Pantoprazole 40mg', 'Pantoprazole 40mg', 'Sun Pharma', 'Gastro', 58.00, 68.00, 40, 110, 15, 'tablets', false, false, '#D1FAE5', '💊', 'images/med_gastro.png'),
(18, 'Pan-D', 'Pantoprazole 40mg + Domperidone 10mg', 'Alkem', 'Gastro', 72.00, 86.00, 35, 95, 15, 'tablets', false, false, '#D1FAE5', '💊', 'images/med_gastro.png'),
(19, 'Razo 20mg', 'Rabeprazole 20mg', 'Sun Pharma', 'Gastro', 85.00, 100.00, 28, 42, 15, 'tablets', false, false, '#D1FAE5', '💊', 'images/med_gastro.png'),
(20, 'Rantac 150', 'Ranitidine 150mg', 'JB Chem', 'Gastro', 38.00, 46.00, 0, 76, 15, 'tablets', false, false, '#D1FAE5', '💊', 'images/med_gastro.png'),
(21, 'Cremaffin', 'Liquid Paraffin + Milk of Magnesia', 'Abbott', 'Gastro', 128.00, 152.00, 15, 28, 225, 'ml', false, false, '#D1FAE5', '🍶', 'images/med_gastro.png'),
(22, 'Digene', 'Magnesium Hydroxide + Aluminium Hydroxide', 'Abbott', 'Gastro', 55.00, 65.00, 50, 89, 10, 'tablets', false, false, '#D1FAE5', '💊', 'images/med_gastro.png'),
(23, 'Ondansetron 4mg', 'Ondansetron 4mg', 'Cipla', 'Gastro', 45.00, 54.00, 22, 39, 10, 'tablets', false, false, '#D1FAE5', '💊', 'images/med_gastro.png'),
(24, 'Nexpro 40', 'Esomeprazole 40mg', 'Torrent', 'Gastro', 92.00, 110.00, 18, 31, 15, 'tablets', false, false, '#D1FAE5', '💊', 'images/med_gastro.png'),
(25, 'Metformin 500mg', 'Metformin HCl 500mg', 'USV', 'Chronic Care', 42.00, 52.00, 60, 160, 20, 'tablets', true, true, '#EDE9FE', '💊', 'images/med_chronic.png'),
(26, 'Glycomet GP1', 'Metformin 500mg + Glimepiride 1mg', 'USV', 'Chronic Care', 78.00, 94.00, 45, 130, 15, 'tablets', true, true, '#EDE9FE', '💊', 'images/med_chronic.png'),
(27, 'Telma 40', 'Telmisartan 40mg', 'Glenmark', 'Chronic Care', 112.00, 135.00, 38, 115, 15, 'tablets', true, true, '#EDE9FE', '💊', 'images/med_chronic.png'),
(28, 'Amlodipine 5mg', 'Amlodipine Besylate 5mg', 'Cipla', 'Chronic Care', 68.00, 82.00, 55, 142, 15, 'tablets', true, true, '#EDE9FE', '💊', 'images/med_chronic.png'),
(29, 'Atorva 10mg', 'Atorvastatin 10mg', 'Zydus', 'Chronic Care', 95.00, 115.00, 42, 88, 15, 'tablets', true, true, '#EDE9FE', '💊', 'images/med_chronic.png'),
(30, 'Ecosprin 75mg', 'Aspirin 75mg', 'USV', 'Chronic Care', 28.00, 34.00, 70, 175, 14, 'tablets', true, true, '#EDE9FE', '💊', 'images/med_chronic.png'),
(31, 'Thyronorm 50mcg', 'Levothyroxine Sodium 50mcg', 'Abbott', 'Chronic Care', 88.00, 105.00, 30, 72, 120, 'tablets', true, true, '#EDE9FE', '💊', 'images/med_chronic.png'),
(32, 'Januvia 50mg', 'Sitagliptin 50mg', 'MSD', 'Chronic Care', 345.00, 415.00, 12, 25, 14, 'tablets', true, true, '#EDE9FE', '💊', 'images/med_chronic.png'),
(33, 'Losartan 50mg', 'Losartan Potassium 50mg', 'Mankind', 'Chronic Care', 72.00, 88.00, 35, 68, 15, 'tablets', true, true, '#EDE9FE', '💊', 'images/med_chronic.png'),
(34, 'Deplatt 75', 'Clopidogrel 75mg', 'Torrent', 'Chronic Care', 85.00, 102.00, 28, 54, 15, 'tablets', true, true, '#EDE9FE', '💊', 'images/med_chronic.png'),
(35, 'Vitamin D3 60K', 'Cholecalciferol 60000IU', 'Mankind', 'Vitamins & Supplements', 145.00, 175.00, 40, 135, 4, 'capsules', false, false, '#FFF7ED', '💊', 'images/med_vitamins.png'),
(36, 'Shelcal 500', 'Calcium Carbonate 1250mg + Vitamin D3 250IU', 'Torrent', 'Vitamins & Supplements', 198.00, 238.00, 35, 112, 30, 'tablets', false, false, '#FFF7ED', '💊', 'images/med_vitamins.png'),
(37, 'Becosules', 'Vitamin B-Complex + Vitamin C', 'Pfizer', 'Vitamins & Supplements', 82.00, 98.00, 55, 165, 20, 'capsules', false, false, '#FFF7ED', '💊', 'images/med_vitamins.png'),
(38, 'Zincovit', 'Multivitamin + Zinc + Antioxidants', 'Apex', 'Vitamins & Supplements', 165.00, 198.00, 28, 82, 15, 'tablets', false, false, '#FFF7ED', '💊', 'images/med_vitamins.png'),
(39, 'Neurobion Forte', 'Vitamin B1 + B6 + B12', 'Merck', 'Vitamins & Supplements', 45.00, 55.00, 65, 140, 30, 'tablets', false, false, '#FFF7ED', '💊', 'images/med_vitamins.png'),
(40, 'Limcee 500mg', 'Ascorbic Acid 500mg', 'Abbott', 'Vitamins & Supplements', 38.00, 46.00, 48, 190, 15, 'tablets', false, false, '#FFF7ED', '💊', 'images/med_vitamins.png'),
(41, 'Evion 400', 'Vitamin E 400mg', 'Merck', 'Vitamins & Supplements', 58.00, 70.00, 40, 98, 30, 'capsules', false, false, '#FFF7ED', '💊', 'images/med_vitamins.png'),
(42, 'Revital H', 'Multivitamin + Minerals + Ginseng', 'Sun Pharma', 'Vitamins & Supplements', 285.00, 342.00, 18, 45, 30, 'capsules', false, false, '#FFF7ED', '💊', 'images/med_vitamins.png'),
(43, 'Betadine Cream', 'Povidone Iodine 5%', 'Win Medicare', 'Skincare', 88.00, 105.00, 20, 62, 25, 'gm', false, false, '#FECDD3', '🧴', 'images/med_skincare.png'),
(44, 'Soframycin', 'Framycetin Sulphate 1%', 'Sanofi', 'Skincare', 78.00, 92.00, 25, 74, 25, 'gm', false, false, '#FECDD3', '🧴', 'images/med_skincare.png'),
(45, 'Fucidin Cream', 'Fusidic Acid 2%', 'Leo Pharma', 'Skincare', 148.00, 178.00, 14, 33, 15, 'gm', false, false, '#FECDD3', '🧴', 'images/med_skincare.png'),
(46, 'Candid Cream', 'Clotrimazole 1%', 'Glenmark', 'Skincare', 72.00, 86.00, 22, 55, 30, 'gm', false, false, '#FECDD3', '🧴', 'images/med_skincare.png'),
(47, 'Fourderm', 'Clotrimazole + Beclomethasone + Neomycin', 'Mankind', 'Skincare', 95.00, 114.00, 0, 80, 30, 'gm', false, false, '#FECDD3', '🧴', 'images/med_skincare.png'),
(48, 'Mometasone Cream', 'Mometasone Furoate 0.1%', 'Sun Pharma', 'Skincare', 112.00, 135.00, 16, 29, 15, 'gm', false, false, '#FECDD3', '🧴', 'images/med_skincare.png'),
(49, 'Calpol 250 Syrup', 'Paracetamol 250mg/5ml', 'GSK', 'Baby Care', 65.00, 78.00, 22, 51, 100, 'ml', false, false, '#E0F2FE', '🍶', 'images/med_baby_care.png'),
(50, 'Colicaid Drops', 'Simethicone 40mg/0.6ml', 'Meyer', 'Baby Care', 88.00, 105.00, 15, 37, 15, 'ml', false, false, '#E0F2FE', '🍶', 'images/med_baby_care.png'),
(51, 'Zinetac Syrup', 'Ranitidine 75mg/5ml', 'GSK', 'Baby Care', 72.00, 86.00, 12, 23, 60, 'ml', false, false, '#E0F2FE', '🍶', 'images/med_baby_care.png'),
(52, 'Bonnisan', 'Dill Oil + Fennel Oil (Herbal)', 'Himalaya', 'Baby Care', 145.00, 174.00, 18, 48, 120, 'ml', false, false, '#E0F2FE', '🍶', 'images/med_baby_care.png'),
(53, 'T-Minic Syrup', 'Triprolidine + Pseudoephedrine', 'GSK', 'Baby Care', 82.00, 98.00, 0, 42, 60, 'ml', false, false, '#E0F2FE', '🍶', 'images/med_baby_care.png'),
(54, 'Allegra 120mg', 'Fexofenadine 120mg', 'Sanofi', 'ENT', 112.00, 134.00, 0, 67, 10, 'tablets', false, false, '#F0FDF4', '💊', 'images/med_ent.png'),
(55, 'Cetirizine 10mg', 'Cetirizine Hydrochloride 10mg', 'Cipla', 'ENT', 28.00, 34.00, 70, 210, 10, 'tablets', false, false, '#F0FDF4', '💊', 'images/med_ent.png'),
(56, 'Montair LC', 'Montelukast 10mg + Levocetirizine 5mg', 'Cipla', 'ENT', 145.00, 174.00, 25, 95, 10, 'tablets', false, false, '#F0FDF4', '💊', 'images/med_ent.png'),
(57, 'Sinarest', 'Paracetamol 500mg + Chlorpheniramine 2mg + PE 10mg', 'Centaur', 'ENT', 48.00, 58.00, 38, 130, 10, 'tablets', false, false, '#F0FDF4', '💊', 'images/med_ent.png'),
(58, 'Otrivin Nasal', 'Xylometazoline 0.1%', 'Novartis', 'ENT', 88.00, 105.00, 20, 52, 10, 'ml', false, false, '#F0FDF4', '🧴', 'images/med_ent.png')
ON CONFLICT (id) DO UPDATE SET
  stock = EXCLUDED.stock,
  sold = EXCLUDED.sold;

-- SEED DEMO USERS
INSERT INTO public.users (id, name, phone, email, role, addresses) VALUES
('user-chemist', 'Dr. Kirti Agrawal (Pharmacist)', '9876540000', 'chemist@kirtipharma.com', 'admin', '[{"id":"addr-store","tag":"Store","text":"Kirti Medical Store, Near Bus Stand, Gondia - 441601","isDefault":true}]'::jsonb),
('user-customer', 'Kirti Customer', '9876543210', 'customer@kirtipharma.com', 'customer', '[{"id":"addr-home","tag":"Home","text":"Flat 302, Sai Shraddha Apts, Ring Road, Gondia - 441614","isDefault":true}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

-- SEED INITIAL SAMPLE ORDERS
INSERT INTO public.orders (id, customerName, phone, date, placed, status, paymentMethod, paymentStatus, deliveryAddress, items, subtotal, deliveryFee, total, rider, stages, estimatedDelivery) VALUES
('KP-2847', 'Kirti Customer', '9876543210', 'Today', '5:02 PM', 'preparing', 'Google Pay (UPI)', 'Paid', 'Flat 302, Sai Shraddha Apts, Ring Road, Gondia - 441614', '[{"id":1,"name":"Crocin 650mg","brand":"GSK","qty":2,"price":32,"packUnit":"tablets"},{"id":25,"name":"Metformin 500mg","brand":"USV","qty":1,"price":42,"packUnit":"tablets"},{"id":43,"name":"Betadine Cream","brand":"Win Medicare","qty":1,"price":88,"packUnit":"gm"}]'::jsonb, 194.00, 30.00, 224.00, '{"id":"rider-1","name":"Rahul Kurmi","initials":"RK","phone":"+919876543210","distance":"2.1 km","eta":"~18 mins"}'::jsonb, '[{"id":"confirmed","label":"Order Confirmed","time":"5:02 PM","status":"done","icon":"✅"},{"id":"preparing","label":"Being Prepared","time":"In Progress","status":"active","icon":"💊"},{"id":"delivery","label":"Out for Delivery","time":"Pending","status":"pending","icon":"🛵"},{"id":"delivered","label":"Delivered","time":"Pending","status":"pending","icon":"📦"}]'::jsonb, '5:24 PM')
ON CONFLICT (id) DO NOTHING;

-- ADVANCE SEQUENCES FOR NEW INSERTS
SELECT setval(pg_get_serial_sequence('public.medicines', 'id'), COALESCE(MAX(id), 1)) FROM public.medicines;
SELECT setval(pg_get_serial_sequence('public.prescriptions', 'id'), COALESCE(MAX(id), 1)) FROM public.prescriptions;
